---
  - hosts: webserver
    become: true
    tasks:
      - name: sk task1
        command: hostname
  - hosts: webserver
    tasks:
      - name: execute a script
        command: ls
  - hosts: webserver
    become: true
    tasks:
      - name: install ngnix
        apt:   
          name: nginx
          state: present
          update_cache: yes 
  - hosts: webserver
    become: true
    tasks:
      - name: install mysql
        apt:   
          name: mysql-server
          state: present
          update_cache: yes 
      - name: install apache    
        apt:  name={{item}}  state=present update_cache=yes
        with_items:
            - apache2
            - libapache2-mod-wsgi
            - python-pip
            - python-virtualenv
          


